#!/bin/bash

# Copyright (c) 2015.  Dan Brown <dan@likethecolor.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#
# Original author: Dan Brown <dan@likethecolor.org>
#
# Functions for logging
#
color_prefix='\033[40;31m'
color_suffix='\033[0m'

# Write to stdout with date a debug message
# If DEBUG is not set no message will be output
#
# param: message to log
#
function log_debug() {
  if test "$DEBUG" != ''; then
    script_name=$(basename $0)
    echo "[$(date)] DEBUG: [${script_name}]: $@"
  fi
}

# Write to stdout with date a info message
#
# param: message to log
#
function log_info() {
  script_name=$(basename $0)
  echo "[$(date)]  INFO: [${script_name}]: $@"
}

# Write to stderr with date a error message
#
# param: message to log
#
function log_error() {
  log_stderr "$@"
}

# Write to stdout with date
#
# param: message to log
#
function log_stdout() {
  script_name=$(basename $0)
  echo "[$(date)]  INFO: [${script_name}]: $@"
}

# Write a separator to stdout with date
#
function log_stdout_sep() {
  log_stdout "** =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- **"
}

# Write to stderr with date and 'ERROR'
#
# param: message to log
#
function log_stderr() {
  if test "x$@" != 'x'; then
    script_name=$(basename $0)
    echo -e "[$(date)] ERROR: [${script_name}]: $color_prefix$@$color_suffix" >&2
  fi
}

# Writes 'exiting' to stderr
#
function log_stderr_exiting() {
	log_stderr 'exiting'
}
